# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31818f6e18b384d5b2cac3aa77dcafffbfd8b82933513bbbdaf181453fcb74ef9fcf96acdc512d3abcaa25582bcc9de8ce0734c429cd5828c274e116f15581e

test:
  secret_key_base: a8bce8a2796a840cae6786b6d8c56ce51482ad5e4a535dc56926f945a05114d00b8db5774c822ac3d7af017232ec9c187f688bfe18a21d5b9711e79ffc0c9611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
